package com.energymonitor.recommendation.adapter.in.web;

import com.energymonitor.recommendation.adapter.in.web.dto.RecommendationResponse;
import com.energymonitor.recommendation.application.port.in.RecommendationInbox;
import com.energymonitor.recommendation.application.port.in.RecommendationView;
import java.util.List;
import java.util.Map;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;

/**
 * Controller for the recommendation inbox.
 *
 * <p>There is no POST: recommendations are generated by the system from the consumption of the
 * home. Only members of the home see, read or delete them; anything else is a 404.
 */
@RestController
@RequestMapping("/api/v1/recommendations")
public class RecommendationController {

    private final RecommendationInbox inbox;
    private final CurrentUserResolver currentUser;

    public RecommendationController(RecommendationInbox inbox, CurrentUserResolver currentUser) {
        this.inbox = inbox;
        this.currentUser = currentUser;
    }

    @GetMapping
    public List<RecommendationResponse> list(@RequestParam String homeId) {
        return inbox.list(currentUser.resolveCurrentUserId(), homeId).stream()
                .map(RecommendationController::toResponse)
                .toList();
    }

    @PutMapping("/{idRecommendation}/read")
    public RecommendationResponse markRead(@PathVariable String idRecommendation) {
        return toResponse(inbox.markRead(currentUser.resolveCurrentUserId(), idRecommendation));
    }

    /** Removes a read recommendation; an unread one is a 409. */
    @DeleteMapping("/{idRecommendation}")
    @ResponseStatus(HttpStatus.NO_CONTENT)
    public void delete(@PathVariable String idRecommendation) {
        inbox.delete(currentUser.resolveCurrentUserId(), idRecommendation);
    }

    /** Removes every read recommendation of a home. */
    @DeleteMapping
    public Map<String, Integer> deleteRead(@RequestParam String homeId) {
        return Map.of("deleted", inbox.deleteRead(currentUser.resolveCurrentUserId(), homeId));
    }

    private static RecommendationResponse toResponse(RecommendationView v) {
        return new RecommendationResponse(v.idRecommendation(), v.homeId(), v.deviceId(), v.deviceName(),
                v.type(), v.messageKey(), v.dateTime(), v.status());
    }
}
