package com.energymonitor.notification.adapter.in.event;

import com.energymonitor.notification.application.usecase.NotifyAlert;
import com.energymonitor.notification.domain.model.NotificationSourceType;
import com.energymonitor.recommendation.api.RecommendationCreated;
import org.springframework.context.event.EventListener;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Component;

/**
 * Sends every new recommendation by mail and push, like the alerts.
 *
 * <p>Asynchronous: the recommendations are generated by the hourly scheduler, which should not
 * wait for SMTP nor the push services.
 */
@Component
public class RecommendationCreatedListener {

    private final NotifyAlert notifyAlert;

    public RecommendationCreatedListener(NotifyAlert notifyAlert) {
        this.notifyAlert = notifyAlert;
    }

    @Async
    @EventListener
    public void on(RecommendationCreated event) {
        notifyAlert.notify(NotificationSourceType.RECOMMENDATION, event.idRecommendation(), event.homeId(),
                event.deviceId(), event.messageKey());
    }
}
